name: Teste Container
on:
    workflow_dispatch:
jobs:
    build-test:
        runs-on: ubuntu-latest
        services:
            postgre:
                image: postgres:16.3
                env:
                    POSTGRES_PASSWORD: Password123
                    POSTGRES_USER: review
                    POSTGRES_DB: review
                ports:
                    - 5432:5432
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
            -   name: Setup .NET
                uses: actions/setup-dotnet@v4
                with:
                    dotnet-version: 8.0.x
            -   name: Teste de Integração
                env: